import type { Block } from '../types'

export const defaultBlocks: Block[] = [
  // ── Layout ────────────────────────────────────────────────────────────────
  {
    id: 'section',
    label: 'Section',
    category: 'Layout',
    icon: '▭',
    template: () => ({
      type: 'section',
      tag: 'div',
      label: 'Section',
      attrs: {},
      styles: { padding: '40px 20px', 'min-height': '100px', 'background-color': '#ffffff', width: '100%' },
      classes: [],
      content: '',
      children: [],
      draggable: true,
      selectable: true,
      droppable: true,
      locked: false,
    }),
  },
  {
    id: 'container',
    label: 'Container',
    category: 'Layout',
    icon: '□',
    template: () => ({
      type: 'container',
      tag: 'div',
      label: 'Container',
      attrs: {},
      styles: { 'max-width': '1200px', margin: '0 auto', padding: '20px', 'min-height': '50px' },
      classes: [],
      content: '',
      children: [],
      draggable: true,
      selectable: true,
      droppable: true,
      locked: false,
    }),
  },
  {
    id: 'columns-2',
    label: '2 Columns',
    category: 'Layout',
    icon: '⊟',
    template: () => ({
      type: 'columns',
      tag: 'div',
      label: '2 Columns',
      attrs: {},
      styles: { display: 'flex', gap: '20px', width: '100%', 'min-height': '60px' },
      classes: [],
      content: '',
      children: [
        {
          id: '',
          type: 'column',
          tag: 'div',
          label: 'Column',
          attrs: {},
          styles: { flex: '1', 'min-height': '60px', padding: '10px', 'background-color': '#f5f5f5' },
          classes: [],
          content: '',
          children: [],
          draggable: true,
          selectable: true,
          droppable: true,
          locked: false,
        },
        {
          id: '',
          type: 'column',
          tag: 'div',
          label: 'Column',
          attrs: {},
          styles: { flex: '1', 'min-height': '60px', padding: '10px', 'background-color': '#f5f5f5' },
          classes: [],
          content: '',
          children: [],
          draggable: true,
          selectable: true,
          droppable: true,
          locked: false,
        },
      ],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },
  {
    id: 'columns-3',
    label: '3 Columns',
    category: 'Layout',
    icon: '⊞',
    template: () => ({
      type: 'columns',
      tag: 'div',
      label: '3 Columns',
      attrs: {},
      styles: { display: 'flex', gap: '20px', width: '100%', 'min-height': '60px' },
      classes: [],
      content: '',
      children: ['Column 1', 'Column 2', 'Column 3'].map((label) => ({
        id: '',
        type: 'column',
        tag: 'div',
        label,
        attrs: {},
        styles: { flex: '1', 'min-height': '60px', padding: '10px', 'background-color': '#f5f5f5' },
        classes: [],
        content: '',
        children: [],
        draggable: true,
        selectable: true,
        droppable: true,
        locked: false,
      })),
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },

  // ── Basic ─────────────────────────────────────────────────────────────────
  {
    id: 'heading',
    label: 'Heading',
    category: 'Basic',
    icon: 'H',
    template: () => ({
      type: 'heading',
      tag: 'h1',
      label: 'Heading',
      attrs: {},
      styles: { 'font-size': '36px', 'font-weight': 'bold', color: '#1a1a1a', 'margin-bottom': '16px', 'line-height': '1.2' },
      classes: [],
      content: 'Heading Text',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },
  {
    id: 'text',
    label: 'Text',
    category: 'Basic',
    icon: 'T',
    template: () => ({
      type: 'text',
      tag: 'p',
      label: 'Text',
      attrs: {},
      styles: { 'font-size': '16px', color: '#4a4a4a', 'line-height': '1.6', 'margin-bottom': '12px' },
      classes: [],
      content: 'Write your text here...',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },
  {
    id: 'button',
    label: 'Button',
    category: 'Basic',
    icon: '⬛',
    template: () => ({
      type: 'button',
      tag: 'button',
      label: 'Button',
      attrs: { type: 'button' },
      styles: {
        'background-color': '#007bff',
        color: '#ffffff',
        padding: '12px 24px',
        border: 'none',
        'border-radius': '4px',
        'font-size': '16px',
        cursor: 'pointer',
        display: 'inline-block',
      },
      classes: [],
      content: 'Click Me',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },
  {
    id: 'image',
    label: 'Image',
    category: 'Basic',
    icon: '🖼',
    template: () => ({
      type: 'image',
      tag: 'img',
      label: 'Image',
      attrs: {
        src: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='600' height='300'%3E%3Crect width='600' height='300' fill='%23e8edf2'/%3E%3Crect x='240' y='100' width='120' height='80' rx='4' fill='%23b0bec5'/%3E%3Ccircle cx='270' cy='125' r='15' fill='%2390a4ae'/%3E%3Cpolygon points='240,180 300,130 340,160 370,140 400,180' fill='%2378909c'/%3E%3Ctext x='300' y='220' font-family='Arial' font-size='16' fill='%23607d8b' text-anchor='middle'%3EClick Traits to set image URL%3C/text%3E%3C/svg%3E",
        alt: 'Image',
      },
      styles: { width: '100%', height: 'auto', display: 'block' },
      classes: [],
      content: '',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },
  {
    id: 'link',
    label: 'Link',
    category: 'Basic',
    icon: '🔗',
    template: () => ({
      type: 'link',
      tag: 'a',
      label: 'Link',
      attrs: { href: '#' },
      styles: { color: '#007bff', 'text-decoration': 'underline', 'font-size': '16px' },
      classes: [],
      content: 'Click here',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },
  {
    id: 'divider',
    label: 'Divider',
    category: 'Basic',
    icon: '—',
    template: () => ({
      type: 'divider',
      tag: 'hr',
      label: 'Divider',
      attrs: {},
      styles: { border: 'none', 'border-top': '1px solid #e0e0e0', margin: '20px 0', width: '100%' },
      classes: [],
      content: '',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },

  // ── Media ─────────────────────────────────────────────────────────────────
  {
    id: 'video',
    label: 'Video',
    category: 'Media',
    icon: '▶',
    template: () => ({
      type: 'video',
      tag: 'video',
      label: 'Video',
      attrs: { controls: 'true', src: '' },
      styles: { width: '100%', height: 'auto', display: 'block' },
      classes: [],
      content: '',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },

  // ── Forms ─────────────────────────────────────────────────────────────────
  {
    id: 'input',
    label: 'Input',
    category: 'Forms',
    icon: '▬',
    template: () => ({
      type: 'input',
      tag: 'input',
      label: 'Input',
      attrs: { type: 'text', placeholder: 'Enter text...' },
      styles: {
        width: '100%',
        padding: '10px 14px',
        border: '1px solid #ccc',
        'border-radius': '4px',
        'font-size': '16px',
        outline: 'none',
      },
      classes: [],
      content: '',
      children: [],
      draggable: true,
      selectable: true,
      droppable: false,
      locked: false,
    }),
  },
]

export const blockCategories = [...new Set(defaultBlocks.map((b) => b.category))]
